<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>service_tray_ng</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>service-tray-ng</AssemblyName>
    <Version>0.1.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\opencode-logo-light.png" />
    <EmbeddedResource Include="Assets\opencode-logo-dark.png" />
    <EmbeddedResource Include="Assets\dsh-logo-light.png" />
    <EmbeddedResource Include="Assets\dsh-logo-dark.png" />
  </ItemGroup>

</Project>
